extends: ['./.eslintrc.yml', 'plugin:@typescript-eslint/recommended']

parserOptions: { 'project': './tsconfig.json' }

rules:
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-use-before-define': 'off'
  '@typescript-eslint/no-explicit-any': 'error'
